### PR TITLE
TUP-2674: Upgrade CXF jar to v3.1 in tWebService

### PR DESCRIPTION
**Pull request by lwang-talend**

### CODE REVIEW

**Comment by amarkevich** [comment]
Can be existing dependencies used for this component?
<IMPORT MODULE_GROUP="cxf-rt-frontend-jaxws" REQUIRED="true" />

**Comment by amarkevich** [comment]
CXF part of org.talend.libraries.esb can be refactored to be org.talend.libraries.apache.cxf

**Comment by nrousseau** [comment]
org.talend.libraries.apache.cxf is included in every builds from TOS, so yes, you can reuse those jars.

**Comment by nrousseau** [comment]
FYI, merged in another pull request.

**Pull request closed without merging**
